<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlayersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table("players")->insert([
            ["usuario"=>"Luciano123AB","email"=>"luciano@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"BR","foto"=>"nenhuma","nivel"=>70,"xp"=>100.0,"quantidade_vitorias"=>300,"quantidade_derrotas"=>45,"id_personagem"=>2,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Joao123AB","email"=>"joao@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"PT","foto"=>"nenhuma","nivel"=>5,"xp"=>75.0,"quantidade_vitorias"=>3,"quantidade_derrotas"=>1,"id_personagem"=>1,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Maria123AB","email"=>"maria@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"ES","foto"=>"nenhuma","nivel"=>8,"xp"=>40.0,"quantidade_vitorias"=>6,"quantidade_derrotas"=>4,"id_personagem"=>2,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Pedro123AB","email"=>"pedro@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"AR","foto"=>"nenhuma","nivel"=>12,"xp"=>90.0,"quantidade_vitorias"=>15,"quantidade_derrotas"=>2,"id_personagem"=>3,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Ana123AB","email"=>"ana@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"US","foto"=>"nenhuma","nivel"=>20,"xp"=>55.0,"quantidade_vitorias"=>22,"quantidade_derrotas"=>10,"id_personagem"=>1,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Lucas123AB","email"=>"lucas@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"MX","foto"=>"nenhuma","nivel"=>18,"xp"=>10.0,"quantidade_vitorias"=>19,"quantidade_derrotas"=>8,"id_personagem"=>2,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Julia123AB","email"=>"julia@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"IT","foto"=>"nenhuma","nivel"=>25,"xp"=>99.0,"quantidade_vitorias"=>40,"quantidade_derrotas"=>11,"id_personagem"=>3,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Gabriel123AB","email"=>"gabriel@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"DE","foto"=>"nenhuma","nivel"=>30,"xp"=>22.0,"quantidade_vitorias"=>50,"quantidade_derrotas"=>17,"id_personagem"=>1,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Beatriz123AB","email"=>"beatriz@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"FR","foto"=>"nenhuma","nivel"=>14,"xp"=>60.0,"quantidade_vitorias"=>17,"quantidade_derrotas"=>6,"id_personagem"=>2,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Rafael123AB","email"=>"rafael@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"JP","foto"=>"nenhuma","nivel"=>33,"xp"=>45.0,"quantidade_vitorias"=>60,"quantidade_derrotas"=>20,"id_personagem"=>3,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Carla123AB","email"=>"carla@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"CA","foto"=>"nenhuma","nivel"=>10,"xp"=>15.0,"quantidade_vitorias"=>9,"quantidade_derrotas"=>5,"id_personagem"=>1,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Matheus123AB","email"=>"matheus@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"RU","foto"=>"nenhuma","nivel"=>40,"xp"=>70.0,"quantidade_vitorias"=>88,"quantidade_derrotas"=>30,"id_personagem"=>2,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Larissa123AB","email"=>"larissa@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"CN","foto"=>"nenhuma","nivel"=>22,"xp"=>80.0,"quantidade_vitorias"=>34,"quantidade_derrotas"=>14,"id_personagem"=>3,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Vinicius123AB","email"=>"vinicius@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"KR","foto"=>"nenhuma","nivel"=>27,"xp"=>35.0,"quantidade_vitorias"=>41,"quantidade_derrotas"=>16,"id_personagem"=>1,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Renata123AB","email"=>"renata@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"SE","foto"=>"nenhuma","nivel"=>19,"xp"=>44.0,"quantidade_vitorias"=>21,"quantidade_derrotas"=>9,"id_personagem"=>2,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Bruno123AB","email"=>"bruno@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"NO","foto"=>"nenhuma","nivel"=>55,"xp"=>10.0,"quantidade_vitorias"=>120,"quantidade_derrotas"=>40,"id_personagem"=>3,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Camila123AB","email"=>"camila@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"CH","foto"=>"nenhuma","nivel"=>35,"xp"=>65.0,"quantidade_vitorias"=>68,"quantidade_derrotas"=>20,"id_personagem"=>1,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Diego123AB","email"=>"diego@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"ZA","foto"=>"nenhuma","nivel"=>48,"xp"=>50.0,"quantidade_vitorias"=>95,"quantidade_derrotas"=>33,"id_personagem"=>2,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Paula123AB","email"=>"paula@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"EG","foto"=>"nenhuma","nivel"=>16,"xp"=>20.0,"quantidade_vitorias"=>15,"quantidade_derrotas"=>10,"id_personagem"=>3,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Andre123AB","email"=>"andre@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"IN","foto"=>"nenhuma","nivel"=>60,"xp"=>95.0,"quantidade_vitorias"=>150,"quantidade_derrotas"=>50,"id_personagem"=>1,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Leticia123AB","email"=>"leticia@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"AU","foto"=>"nenhuma","nivel"=>28,"xp"=>78.0,"quantidade_vitorias"=>55,"quantidade_derrotas"=>21,"id_personagem"=>2,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Thiago123AB","email"=>"thiago@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"NZ","foto"=>"nenhuma","nivel"=>70,"xp"=>99.0,"quantidade_vitorias"=>250,"quantidade_derrotas"=>90,"id_personagem"=>3,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Aline123AB","email"=>"aline@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"CL","foto"=>"nenhuma","nivel"=>24,"xp"=>58.0,"quantidade_vitorias"=>44,"quantidade_derrotas"=>19,"id_personagem"=>1,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Felipe123AB","email"=>"felipe@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"PL","foto"=>"nenhuma","nivel"=>45,"xp"=>32.0,"quantidade_vitorias"=>90,"quantidade_derrotas"=>30,"id_personagem"=>2,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Sofia123AB","email"=>"sofia@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"UA","foto"=>"nenhuma","nivel"=>13,"xp"=>25.0,"quantidade_vitorias"=>12,"quantidade_derrotas"=>7,"id_personagem"=>3,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Igor123AB","email"=>"igor@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"RO","foto"=>"nenhuma","nivel"=>38,"xp"=>66.0,"quantidade_vitorias"=>72,"quantidade_derrotas"=>24,"id_personagem"=>1,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Carol123AB","email"=>"carol@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Outro","pais"=>"IE","foto"=>"nenhuma","nivel"=>21,"xp"=>47.0,"quantidade_vitorias"=>30,"quantidade_derrotas"=>15,"id_personagem"=>2,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Samuel123AB","email"=>"samuel@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"FI","foto"=>"nenhuma","nivel"=>52,"xp"=>82.0,"quantidade_vitorias"=>110,"quantidade_derrotas"=>44,"id_personagem"=>3,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Natalia123AB","email"=>"natalia@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"DK","foto"=>"nenhuma","nivel"=>18,"xp"=>36.0,"quantidade_vitorias"=>19,"quantidade_derrotas"=>11,"id_personagem"=>1,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Eduardo123AB","email"=>"eduardo@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"NL","foto"=>"nenhuma","nivel"=>65,"xp"=>12.0,"quantidade_vitorias"=>170,"quantidade_derrotas"=>60,"id_personagem"=>2,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Patricia123AB","email"=>"patricia@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"BE","foto"=>"nenhuma","nivel"=>29,"xp"=>93.0,"quantidade_vitorias"=>58,"quantidade_derrotas"=>23,"id_personagem"=>3,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Leonardo123AB","email"=>"leonardo@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"AT","foto"=>"nenhuma","nivel"=>42,"xp"=>61.0,"quantidade_vitorias"=>85,"quantidade_derrotas"=>29,"id_personagem"=>1,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Monica123AB","email"=>"monica@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"GR","foto"=>"nenhuma","nivel"=>34,"xp"=>78.0,"quantidade_vitorias"=>70,"quantidade_derrotas"=>26,"id_personagem"=>2,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Daniel123AB","email"=>"daniel@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"TR","foto"=>"nenhuma","nivel"=>50,"xp"=>40.0,"quantidade_vitorias"=>100,"quantidade_derrotas"=>40,"id_personagem"=>3,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Vanessa123AB","email"=>"vanessa@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"IL","foto"=>"nenhuma","nivel"=>26,"xp"=>69.0,"quantidade_vitorias"=>49,"quantidade_derrotas"=>18,"id_personagem"=>1,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Marcos123AB","email"=>"marcos@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"AE","foto"=>"nenhuma","nivel"=>58,"xp"=>88.0,"quantidade_vitorias"=>130,"quantidade_derrotas"=>55,"id_personagem"=>2,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Ricardo123AB","email"=>"ricardo@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"SA","foto"=>"nenhuma","nivel"=>31,"xp"=>54.0,"quantidade_vitorias"=>62,"quantidade_derrotas"=>21,"id_personagem"=>1,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Fernanda123AB","email"=>"fernanda@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"IR","foto"=>"nenhuma","nivel"=>23,"xp"=>48.0,"quantidade_vitorias"=>39,"quantidade_derrotas"=>17,"id_personagem"=>2,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Gustavo123AB","email"=>"gustavo@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"TH","foto"=>"nenhuma","nivel"=>46,"xp"=>71.0,"quantidade_vitorias"=>92,"quantidade_derrotas"=>28,"id_personagem"=>3,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Priscila123AB","email"=>"priscila@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"PH","foto"=>"nenhuma","nivel"=>17,"xp"=>29.0,"quantidade_vitorias"=>18,"quantidade_derrotas"=>9,"id_personagem"=>1,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Hugo123AB","email"=>"hugo@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"VN","foto"=>"nenhuma","nivel"=>39,"xp"=>83.0,"quantidade_vitorias"=>79,"quantidade_derrotas"=>26,"id_personagem"=>2,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Bianca123AB","email"=>"bianca@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"ID","foto"=>"nenhuma","nivel"=>27,"xp"=>66.0,"quantidade_vitorias"=>51,"quantidade_derrotas"=>20,"id_personagem"=>3,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Caio123AB","email"=>"caio@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"MY","foto"=>"nenhuma","nivel"=>44,"xp"=>15.0,"quantidade_vitorias"=>87,"quantidade_derrotas"=>35,"id_personagem"=>1,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Daniela123AB","email"=>"daniela@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"SG","foto"=>"nenhuma","nivel"=>21,"xp"=>50.0,"quantidade_vitorias"=>33,"quantidade_derrotas"=>14,"id_personagem"=>2,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Rodrigo123AB","email"=>"rodrigo@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"QA","foto"=>"nenhuma","nivel"=>59,"xp"=>92.0,"quantidade_vitorias"=>140,"quantidade_derrotas"=>57,"id_personagem"=>3,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Tais123AB","email"=>"tais@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"KW","foto"=>"nenhuma","nivel"=>15,"xp"=>18.0,"quantidade_vitorias"=>14,"quantidade_derrotas"=>8,"id_personagem"=>1,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Alex123AB","email"=>"alex@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Outro","pais"=>"OM","foto"=>"nenhuma","nivel"=>36,"xp"=>74.0,"quantidade_vitorias"=>69,"quantidade_derrotas"=>31,"id_personagem"=>2,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Isabela123AB","email"=>"isabela@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"MA","foto"=>"nenhuma","nivel"=>32,"xp"=>61.0,"quantidade_vitorias"=>64,"quantidade_derrotas"=>25,"id_personagem"=>3,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Otavio123AB","email"=>"otavio@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Masculino","pais"=>"TN","foto"=>"nenhuma","nivel"=>41,"xp"=>89.0,"quantidade_vitorias"=>81,"quantidade_derrotas"=>29,"id_personagem"=>1,"created_at"=>date("Y-m-d H:i:s")],
            ["usuario"=>"Yasmin123AB","email"=>"yasmin@gmail.com","senha"=>encrypt("24032004ABCD123"),"genero"=>"Feminino","pais"=>"NG","foto"=>"nenhuma","nivel"=>19,"xp"=>34.0,"quantidade_vitorias"=>22,"quantidade_derrotas"=>11,"id_personagem"=>2,"created_at"=>date("Y-m-d H:i:s")]
        ]);
    }
}
